#! /bin/sh -e

CMD=$(basename "$0")
TOP=$(dirname $(readlink -f "$0"))
RTL_LIB="$TOP/../examples/lib"

echo $RTL_LIB

if [ $CMD = "y" ]; then
    YOSYS_CMD=$2
else
    YOSYS_CMD=$CMD
fi

yosys -p "read_verilog -I$RTL_LIB $1; synth_ice40; $YOSYS_CMD"
